services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: techpanel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - .docker/db/data:/var/lib/postgresql/data