"""update schema

Revision ID: a0dac15aec5c
Revises: b8c1d2e3f4a5
Create Date: 2026-05-04 21:03:04.001431

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a0dac15aec5c"
down_revision: Union[str, Sequence[str], None] = "b8c1d2e3f4a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
